import { db } from "./db";
import {
  proceedings,
  proceedingEvents,
  deadlines,
  researchDocuments,
  draftTemplates,
  teams,
  clients,
} from "@shared/schema";
import { sql } from "drizzle-orm";

export async function seedDatabase() {
  // Check if data already exists
  const existing = await db.select({ count: sql<number>`count(*)` }).from(proceedings);
  if (Number(existing[0].count) > 0) {
    console.log("Database already seeded, skipping...");
    return;
  }

  console.log("Seeding database with Georgia CON sample data...");

  // Create a demo team
  const [team] = await db.insert(teams).values({ name: "Smith & Associates Health Law" }).returning();

  // Seed proceedings with realistic Georgia CON data
  const proceedingData = [
    {
      caseNumber: "CON2024001",
      proceedingType: "con" as const,
      status: "under_review" as const,
      title: "New 120-Bed Skilled Nursing Facility - Gwinnett County",
      applicant: "Gwinnett Senior Living, LLC",
      applicantEntity: "Gwinnett Senior Living, LLC",
      facilityName: "Gwinnett Gardens Nursing Center",
      facilityType: "Skilled Nursing Facility",
      serviceType: "Long-term Care",
      county: "Gwinnett",
      address: "2500 Sugarloaf Parkway, Lawrenceville, GA 30043",
      latitude: 33.9587,
      longitude: -84.0735,
      filingDate: new Date("2024-09-15"),
      loiDate: new Date("2024-08-10"),
      applicationDate: new Date("2024-09-15"),
      estimatedCost: "$28,500,000",
      bedCount: 120,
      description: "Application to establish a new 120-bed skilled nursing facility in Gwinnett County to address growing demand for long-term care services in the northeast metro Atlanta corridor.",
      laserficheUrl: "https://weblink.dch.georgia.gov/WebLink/Browse.aspx?startid=63&dbid=1",
    },
    {
      caseNumber: "CON2024015",
      proceedingType: "con" as const,
      status: "approved" as const,
      title: "Cardiac Catheterization Lab Addition - Memorial Health",
      applicant: "Memorial Health University Medical Center",
      applicantEntity: "HCA Healthcare",
      facilityName: "Memorial Health University Medical Center",
      facilityType: "Hospital",
      serviceType: "Cardiac Catheterization",
      county: "Chatham",
      address: "4700 Waters Ave, Savannah, GA 31404",
      latitude: 32.0286,
      longitude: -81.0850,
      filingDate: new Date("2024-06-01"),
      loiDate: new Date("2024-05-01"),
      applicationDate: new Date("2024-06-01"),
      hearingDate: new Date("2024-10-15"),
      decisionDate: new Date("2024-11-20"),
      outcome: "approved" as const,
      estimatedCost: "$4,200,000",
      description: "Addition of one cardiac catheterization laboratory to expand existing cardiac services capacity.",
    },
    {
      caseNumber: "CON2025003",
      proceedingType: "con" as const,
      status: "loi_filed" as const,
      title: "Freestanding Emergency Department - Cherokee County",
      applicant: "Northside Hospital Cherokee",
      applicantEntity: "Northside Hospital, Inc.",
      facilityName: "Northside Hospital Cherokee ED - Holly Springs",
      facilityType: "Freestanding Emergency Department",
      serviceType: "Emergency Services",
      county: "Cherokee",
      address: "Holly Springs, GA 30115",
      latitude: 34.1748,
      longitude: -84.4963,
      filingDate: new Date("2025-01-10"),
      loiDate: new Date("2025-01-10"),
      estimatedCost: "$18,000,000",
      description: "Letter of Intent to establish a freestanding emergency department in the Holly Springs area of Cherokee County.",
    },
    {
      caseNumber: "DET2024038",
      proceedingType: "det" as const,
      status: "determination_issued" as const,
      title: "Bed Reclassification - Piedmont Atlanta Hospital",
      applicant: "Piedmont Healthcare",
      applicantEntity: "Piedmont Healthcare, Inc.",
      facilityName: "Piedmont Atlanta Hospital",
      facilityType: "Hospital",
      serviceType: "Acute Care",
      county: "Fulton",
      address: "1968 Peachtree Rd NW, Atlanta, GA 30309",
      latitude: 33.8060,
      longitude: -84.3854,
      filingDate: new Date("2024-07-20"),
      decisionDate: new Date("2024-09-05"),
      description: "Request for determination regarding reclassification of 30 medical/surgical beds to rehabilitation beds.",
    },
    {
      caseNumber: "DET-EQT2024012",
      proceedingType: "det_eqt" as const,
      status: "request_filed" as const,
      title: "MRI Replacement - Emory Johns Creek Hospital",
      applicant: "Emory Healthcare",
      applicantEntity: "Emory Healthcare, Inc.",
      facilityName: "Emory Johns Creek Hospital",
      facilityType: "Hospital",
      serviceType: "Diagnostic Imaging",
      county: "Fulton",
      address: "6325 Hospital Pkwy, Johns Creek, GA 30097",
      latitude: 34.0365,
      longitude: -84.1838,
      filingDate: new Date("2024-11-01"),
      equipmentType: "MRI - 3.0 Tesla",
      estimatedCost: "$3,800,000",
      description: "Equipment determination request for replacement of existing 1.5T MRI with new 3.0T MRI system.",
    },
    {
      caseNumber: "DET-EQT2025001",
      proceedingType: "det_eqt" as const,
      status: "under_review" as const,
      title: "CT Scanner Acquisition - Phoebe Putney Memorial",
      applicant: "Phoebe Putney Health System",
      applicantEntity: "Phoebe Putney Health System, Inc.",
      facilityName: "Phoebe Putney Memorial Hospital",
      facilityType: "Hospital",
      serviceType: "Diagnostic Imaging",
      county: "Dougherty",
      address: "417 W Third Ave, Albany, GA 31701",
      latitude: 31.5808,
      longitude: -84.1602,
      filingDate: new Date("2025-01-15"),
      equipmentType: "CT Scanner - 256 Slice",
      estimatedCost: "$2,100,000",
      description: "Request for equipment determination for acquisition of additional CT scanner to address increasing patient volume.",
    },
    {
      caseNumber: "DET-ASC2024005",
      proceedingType: "det_asc" as const,
      status: "determination_issued" as const,
      title: "Single Specialty ASC - Georgia Orthopedic Associates",
      applicant: "Georgia Orthopedic Associates, P.C.",
      applicantEntity: "Georgia Orthopedic Associates, P.C.",
      facilityName: "Georgia Orthopedic Ambulatory Surgery Center",
      facilityType: "Ambulatory Surgery Center",
      serviceType: "Orthopedic Surgery",
      county: "Bibb",
      address: "3780 Northside Dr, Macon, GA 31210",
      latitude: 32.8735,
      longitude: -83.7102,
      filingDate: new Date("2024-04-15"),
      decisionDate: new Date("2024-06-30"),
      operatingRooms: 2,
      estimatedCost: "$2,200,000",
      description: "Determination request for establishment of physician-owned single specialty ambulatory surgery center for orthopedic procedures.",
    },
    {
      caseNumber: "CON2024022",
      proceedingType: "con" as const,
      status: "appeal_filed" as const,
      title: "New Hospital - South Forsyth",
      applicant: "Wellstar Health System",
      applicantEntity: "Wellstar Health System, Inc.",
      facilityName: "Wellstar South Forsyth Hospital",
      facilityType: "Hospital",
      serviceType: "General Acute Care",
      county: "Forsyth",
      address: "South Forsyth, GA 30041",
      latitude: 34.1377,
      longitude: -84.1402,
      filingDate: new Date("2024-03-01"),
      loiDate: new Date("2024-02-01"),
      applicationDate: new Date("2024-03-01"),
      hearingDate: new Date("2024-08-20"),
      decisionDate: new Date("2024-10-01"),
      appealDeadline: new Date("2024-11-01"),
      outcome: "denied" as const,
      estimatedCost: "$185,000,000",
      bedCount: 100,
      description: "Application for new 100-bed general acute care hospital in south Forsyth County. Denied; currently under appeal.",
    },
    {
      caseNumber: "DET-ASC2025002",
      proceedingType: "det_asc" as const,
      status: "request_filed" as const,
      title: "GI Endoscopy Center - Digestive Health Associates",
      applicant: "Digestive Health Associates of Georgia",
      applicantEntity: "Digestive Health Associates of Georgia, P.C.",
      facilityName: "North Georgia Endoscopy Center",
      facilityType: "Ambulatory Surgery Center",
      serviceType: "Gastroenterology",
      county: "Hall",
      address: "1140 Jesse Jewell Pkwy, Gainesville, GA 30501",
      latitude: 34.2979,
      longitude: -83.8241,
      filingDate: new Date("2025-02-01"),
      operatingRooms: 3,
      estimatedCost: "$3,500,000",
      description: "Request for determination for establishment of physician-owned single specialty ambulatory surgery center for GI endoscopy procedures.",
    },
    {
      caseNumber: "CON2024030",
      proceedingType: "con" as const,
      status: "pending_decision" as const,
      title: "Psychiatric Hospital Expansion - Ridgeview Institute",
      applicant: "Ridgeview Institute",
      applicantEntity: "Universal Health Services, Inc.",
      facilityName: "Ridgeview Institute",
      facilityType: "Psychiatric Hospital",
      serviceType: "Behavioral Health",
      county: "Cobb",
      address: "3995 S Cobb Dr SE, Smyrna, GA 30080",
      latitude: 33.8520,
      longitude: -84.5180,
      filingDate: new Date("2024-08-15"),
      loiDate: new Date("2024-07-10"),
      applicationDate: new Date("2024-08-15"),
      hearingDate: new Date("2025-01-20"),
      estimatedCost: "$22,000,000",
      bedCount: 60,
      description: "Application to expand psychiatric hospital by 60 beds to address growing behavioral health needs in the metro Atlanta region.",
    },
  ];

  const insertedProceedings = await db.insert(proceedings).values(proceedingData).returning();

  // Seed events
  const eventData = [
    {
      proceedingId: insertedProceedings[0].id,
      title: "Letter of Intent Filed",
      description: "LOI submitted to DCH Office of Health Planning",
      eventDate: new Date("2024-08-10"),
      eventType: "loi_filed",
      source: "manual",
    },
    {
      proceedingId: insertedProceedings[0].id,
      title: "Application Filed",
      description: "Complete CON application submitted with $28.5M project budget",
      eventDate: new Date("2024-09-15"),
      eventType: "application_filed",
      source: "manual",
    },
    {
      proceedingId: insertedProceedings[0].id,
      title: "Application Deemed Complete",
      description: "DCH confirmed application is complete and under review",
      eventDate: new Date("2024-10-01"),
      eventType: "status_change",
      source: "tracking_report",
    },
    {
      proceedingId: insertedProceedings[1].id,
      title: "CON Approved",
      description: "DCH approved cardiac cath lab addition",
      eventDate: new Date("2024-11-20"),
      eventType: "decision",
      source: "tracking_report",
    },
    {
      proceedingId: insertedProceedings[7].id,
      title: "CON Denied",
      description: "Application denied - insufficient need demonstrated",
      eventDate: new Date("2024-10-01"),
      eventType: "decision",
      source: "tracking_report",
    },
    {
      proceedingId: insertedProceedings[7].id,
      title: "Appeal Filed",
      description: "Wellstar filed appeal to CON Appeal Panel",
      eventDate: new Date("2024-10-25"),
      eventType: "appeal_filed",
      source: "manual",
    },
  ];

  await db.insert(proceedingEvents).values(eventData);

  // Seed deadlines
  await db.insert(deadlines).values([
    {
      proceedingId: insertedProceedings[2].id,
      title: "CON Application Due",
      description: "Application must be filed within 30 days of LOI",
      dueDate: new Date("2025-02-09"),
      deadlineType: "application_due" as const,
      isAutoGenerated: true,
      reminderDaysBefore: [1, 3, 7, 14],
    },
    {
      proceedingId: insertedProceedings[7].id,
      title: "Appeal Hearing",
      description: "CON Appeal Panel hearing scheduled",
      dueDate: new Date("2025-03-15"),
      deadlineType: "hearing" as const,
      isAutoGenerated: false,
      reminderDaysBefore: [1, 3, 7],
    },
    {
      proceedingId: insertedProceedings[9].id,
      title: "Expected Decision Date",
      description: "DCH expected to issue decision following hearing",
      dueDate: new Date("2025-04-15"),
      deadlineType: "custom" as const,
      isAutoGenerated: false,
      reminderDaysBefore: [1, 7, 14],
    },
  ]);

  // Seed client
  await db.insert(clients).values({
    teamId: team.id,
    name: "Piedmont Healthcare - Atlanta Campus",
    facilityType: "Hospital",
    address: "1968 Peachtree Rd NW, Atlanta, GA 30309",
    county: "Fulton",
    latitude: 33.8060,
    longitude: -84.3854,
    monitoringRadiusMiles: 30,
  });

  // Seed research documents
  await db.insert(researchDocuments).values([
    {
      title: "Georgia CON Rules - Chapter 111-2-2",
      category: "Regulations",
      description: "Complete text of Georgia Certificate of Need administrative rules",
      tags: ["rules", "regulations", "111-2-2"],
      sourceUrl: "https://dch.georgia.gov/divisionsoffices/office-health-planning/certificate-need-con/state-health-plans-and-con-rules",
    },
    {
      title: "O.C.G.A. Chapter 31-6 - Certificate of Need",
      category: "Statute",
      description: "Georgia Code - Certificate of Need enabling statute",
      tags: ["statute", "OCGA", "31-6"],
    },
    {
      title: "HB 1339 - 2024 CON Statute Amendments",
      category: "Legislation",
      description: "House Bill 1339 modifications to Georgia CON statute, effective July 1, 2024",
      tags: ["legislation", "HB1339", "2024", "amendments"],
    },
    {
      title: "CON Thresholds - Effective July 1, 2025",
      category: "Reference",
      description: "Current CON capital expenditure thresholds and triggers",
      tags: ["thresholds", "capital expenditure"],
      sourceUrl: "https://dch.georgia.gov/divisionsoffices/office-health-planning/certificate-need-con/con-thresholds",
    },
  ]);

  // Seed draft templates
  await db.insert(draftTemplates).values([
    {
      name: "CON Opposition Letter",
      category: "Opposition",
      description: "Template for opposing a Certificate of Need application",
      templateContent: `[Date]\n\nGeorgia Department of Community Health\nOffice of Health Planning\n2 Peachtree Street NW, Suite 36.470\nAtlanta, Georgia 30303\n\nRE: Notice of Opposition - [Case Number]\n    [Applicant Name] - [Project Description]\n\nDear Director:\n\nPursuant to Rule 111-2-2-.08 of the Georgia Certificate of Need Rules, [Client Name] hereby submits this Notice of Opposition to the above-referenced application.\n\n[Client Name] opposes this application for the following reasons:\n\n1. NEED: [Analysis of need projection data and community need]\n\n2. FINANCIAL FEASIBILITY: [Analysis of financial projections]\n\n3. IMPACT ON EXISTING PROVIDERS: [Analysis of impact on existing services]\n\n4. QUALITY OF CARE: [Quality considerations]\n\nFor the foregoing reasons, [Client Name] respectfully requests that the Department deny this application.\n\nRespectfully submitted,\n\n[Attorney Name]\n[Firm Name]\nCounsel for [Client Name]`,
    },
    {
      name: "CON Application Cover Letter",
      category: "Application",
      description: "Cover letter for CON application submission",
      templateContent: `[Date]\n\nGeorgia Department of Community Health\nOffice of Health Planning\n2 Peachtree Street NW, Suite 36.470\nAtlanta, Georgia 30303\n\nRE: Certificate of Need Application - [Project Description]\n    [Applicant Name]\n\nDear Director:\n\nOn behalf of [Applicant Name], enclosed please find the Certificate of Need Application for [Project Description] in [County] County, Georgia.\n\nThe application includes:\n- Completed CON Application Form\n- Required supplemental forms\n- Filing fee of $[Amount]\n- Supporting documentation\n\nPlease contact the undersigned with any questions.\n\nRespectfully submitted,\n\n[Attorney Name]\n[Firm Name]`,
    },
    {
      name: "Determination Request Letter",
      category: "Determination",
      description: "Template for requesting a Letter of Determination from DCH",
      templateContent: `[Date]\n\nGeorgia Department of Community Health\nOffice of Health Planning\n2 Peachtree Street NW, Suite 36.470\nAtlanta, Georgia 30303\n\nRE: Request for Letter of Determination\n    [Requestor Name] - [Project Description]\n\nDear Director:\n\nPursuant to O.C.G.A. Section 31-6-40(c) and Rule 111-2-2-.26, [Requestor Name] hereby requests a written determination from the Department regarding whether Certificate of Need requirements apply to the following proposed project:\n\nPROJECT DESCRIPTION:\n[Detailed description of the proposed project]\n\nAPPLICABLE EXEMPTIONS:\n[Analysis of potentially applicable CON exemptions]\n\nEnclosed please find the filing fee of $250.00.\n\nRespectfully submitted,\n\n[Attorney Name]\n[Firm Name]`,
    },
  ]);

  console.log(
    `Seeded: ${insertedProceedings.length} proceedings, ${eventData.length} events, 3 deadlines, 1 team, 1 client, 4 research docs, 3 templates`
  );
}
